### ISSUE TITLE
Federator doesn't start 

### ISSUE THREAD

**Issue by PraneshASP** [rsksmart/tokenbridge#292]
Hi, I was trying to deploy and test the bridgeon Kovan < > RSK Testnet.
The contracts have been deployed successfully, but when I try to run the federator -> `npm run start` it throws the following error

```sh
  npm run start

> federator@2.0.1 start  /tokenbridge/federator
> node ./src/main.js

[2021-12-12T22:49:02.708] [INFO] Federators - RSK Host https://public-node.testnet.rsk.co/
[2021-12-12T22:49:02.710] [INFO] Federators - ETH Host https://kovan.infura.io/v3/<INFURA_KEY>
[2021-12-12T22:49:02.790] [INFO] Federators - start scheduler service polling every 120000(ms)
[2021-12-12T22:49:02.790] [INFO] Federators - scheduler triggered poll
[2021-12-12T22:49:02.809] [INFO] Federators - listening on http://localhost:5000/
[2021-12-12T22:49:04.033] [INFO] Federators - start scheduler service polling every 3600000(ms)
[2021-12-12T22:49:04.033] [INFO] Federators - scheduler triggered poll
[2021-12-12T22:49:04.643] [ERROR] MAIN-FEDERATOR - Error: Exception Running Federator
    at Federator.run ( /tokenbridge/federator/src/lib/Federator.js:91:35)
    at async run ( /tokenbridge/federator/src/main.js:50:9)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9) Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html>\n  <head>\n    <title>403 Method Not Allowed</title>\n  </head>\n  <body>\n    <h1>Error 403 Method Not Allowed</h1>\n    <p>Method Not Allowed</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 167848944</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n"
    at Object.InvalidResponse ( /tokenbridge/federator/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange ( /tokenbridge/federator/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[2021-12-12T22:49:04.645] [DEBUG] MAIN-FEDERATOR - Run 1 retrie
CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735485 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:07.683] [ERROR] HEARTBEAT - Error: Exception Running Heartbeat
    at Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:52:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9) CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735485 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:07.683] [DEBUG] HEARTBEAT - Run 1 retrie
CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735486 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:11.643] [ERROR] HEARTBEAT - Error: Exception Running Heartbeat
    at Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:52:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9) CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735486 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:11.643] [DEBUG] HEARTBEAT - Run 2 retrie
[2021-12-12T22:49:15.394] [ERROR] MAIN-FEDERATOR - Error: Exception Running Federator
    at Federator.run ( /tokenbridge/federator/src/lib/Federator.js:91:35)
    at async run ( /tokenbridge/federator/src/main.js:50:9)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9) Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html>\n  <head>\n    <title>403 Method Not Allowed</title>\n  </head>\n  <body>\n    <h1>Error 403 Method Not Allowed</h1>\n    <p>Method Not Allowed</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 174425157</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n"
    at Object.InvalidResponse ( /tokenbridge/federator/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange ( /tokenbridge/federator/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> ( /tokenbridge/federator/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[2021-12-12T22:49:15.394] [DEBUG] MAIN-FEDERATOR - Run 2 retrie
CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735486 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:15.700] [ERROR] HEARTBEAT - Error: Exception Running Heartbeat
    at Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:52:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9) CustomError: Exception Emiting Hearbeat rskBlock: 2412728 ethBlock: 28735486 fedVersion: 2.0.1
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:206:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
 Internal Error: This Federator addr:0xffed4b0dd6225962d8287f6f0ac9f2d3853abb14 is not part of the federation
    at Heartbeat._emitHeartbeat ( /tokenbridge/federator/src/lib/Heartbeat.js:192:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Heartbeat.run ( /tokenbridge/federator/src/lib/Heartbeat.js:43:24)
    at async Object.run ( /tokenbridge/federator/src/main.js:66:21)
    at async Scheduler.poll ( /tokenbridge/federator/src/services/Scheduler.js:24:13)
    at async Scheduler.start ( /tokenbridge/federator/src/services/Scheduler.js:17:9)
[2021-12-12T22:49:15.700] [DEBUG] HEARTBEAT - Run 3 retrie
````

**Comment by pmprete** [comment]
the Error: Invalid JSON RPC response: in the stack trace indicates that this is likely a rate limting error from the RPC endpoint  I assume you are using the public nodes from RSK, the public node does not support the getLogs function as it's very resource consuming.
So you're encouraged to switch to either:
- run your own RSKj node (unlimited RPC requests)
- use a 3rd party RPC endpoint (less limited RPC requests), such as GetBlock: https://developers.rsk.co/solutions/getblock/#top

This conversation is being held at RSK open slack https://open-rsk-dev.slack.com/archives/C01V5UDT4KS/p1639330446027400
